### ISSUE TITLE
nie zmieniać właściciela sdrcfg0.txt

### ISSUE THREAD

**Issue by Wojtus11** [sp9skp/spdxl#2]
Zmiana właściciela plików sdrcfg*.txt uniemożliwia pracę skryptom rotującym częstotliwość.
W spdxl/START zamiast linii:
`chown www-data:www-data /tmp/*.txt`
proponuję linię
`chmod 666 /tmp/*.txt`

**Comment by sp9skp** [comment]
Zrobione
